---
version: '3.3'
services:

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug
# ENTRYPOINT ["node", "./build/cli.node.js"]
# ENTRYPOINT ["node", "/app/ganache-core.docker.cli.js"]

  truffle:
    build:
      context: ./truffle_build_context
      target: truffle
    depends_on:
      - ganache
    volumes:
      - ./:/home/app
      - /home/app/node_modules

  eth-todo-list-frontend:
    build:
      context: ./eth-todo-list
    ports:
      - "3000:3000"
    depends_on:
      - truffle
    volumes:
      - ./:/code/app
      - /code/app/node_modules

networks:
  default:
    name: blockchain

